---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-frontend
  namespace: currency-watcher
  labels:
    app: currency-watcher
    tier: frontend
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: currency-watcher
      tier: frontend
  template:
    metadata:   
      labels: 
        app: currency-watcher
        tier: frontend
    spec:
      nodeSelector:
        storage: ssd
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - currency-watcher
                  - key: tier
                    operator: In
                    values:
                      - frontend
                topologyKey: "kubernetes.io/hostname"
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: web-dashboard
        image: nginx:1.27.5
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: html-volume
        configMap:
          name: frontend-html