apiVersion: v1
kind: Service
metadata:
  name: currency-service
  namespace: currency-watcher
spec:
  type: NodePort
  selector:
    app: currency-watcher
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080